[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.9.2"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404