[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.9.2"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ensure Next.js server-side functions work properly
[functions]
  node_bundler = "esbuild"

# Handle Next.js rewrites and redirects
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_server"
  status = 200

# Enable Next.js image optimization
[[plugins]]
  package = "@netlify/plugin-nextjs/plugin"